# -*- coding: utf-8 -*-
"""GRV2_GAMZE_SÜEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14f0HvRiTemY-Tp0BV6PtTRrDM3VxMSHx

1.Bir listedeki isimlerin baş harflerini yazdıran uygulama
"""

isimler=["Gamze","Fatma","Merve","Cihan"]
for isim in isimler:
    print(isim[0])

"""2. "Tamam" ifadesini görene kadar bir şeyler yazmanı isteyen uygulama (while)"""

deger=""
while deger.lower() !="tamam":

    deger=input("Lütfen birşey yazınız: ")

print ("Tamam ifadesi girdiniz.Çıkış yapılıyor")

"""3. Bir listedeki aynı isimleri teke indirecek bir uygulama"""

isimler=set(["Gamze","Cihan","Merve","Gamze","Merve","Ayten"])
print(list(isimler))

"""4. "Tamam" yazana kadar girdiğiniz kelimeleri, bir listeye ekleyen uygulama"""

kelimeler = []

while True:
    kelime = input("Bir kelime girin ('Tamam' yazana kadar devam edebilirsiniz): ")

    if kelime.lower() == "tamam":
        break

    kelimeler.append(kelime)

print("Girdiğiniz kelimeler:", kelimeler)

"""5. Bir listedeki sadece stringleri döndüren bir döngü oluşturun

"""

liste = ["gamze", "zeynep", 1, 3, 5, "fatma"]
liste2 = []
for i in liste:
    if type(i) == str:
        liste2.append(i)
print(liste2)
if liste == str:
    print(liste)

"""6. liste şeklindeki Celsius değerlerin fahrenayt a çevirecek uygulama"""

fahrenheit =input("Lütfen Fahrenheit değerini giriniz: ")
fahrenheit=float(fahrenheit)
celsius = (fahrenheit - 32) / 1.8
print(f"{fahrenheit} Fahrenheit = {celsius} Celsius")

"""7. Tahmin oyunu  "from random import randint"  randint(0, 100)"""

from random import randint
sayı = randint(0, 100)

while True:

       tahmin = int(input("0 ile 100 arasında bir sayı tahmin edin: "))

       if tahmin < sayı:
        print("Daha yüksek bir sayı tahmin edin.")
        continue
       elif tahmin > sayı:
        print("Daha düşük bir sayı tahmin edin.")
        continue
       else:
        print("Tebrikler! Doğru tahmin ettiniz.")
       break

"""8.  1 den 100 e kadar 3 er 3 er sayan uygulama"""

sayı=1
while sayı<100:
    print(sayı)
    sayı+=3

"""10. Girdiğiniz kelimedeki belirli harfleri yazdıran bir uygulama"""

kelime=input("lütfen kelime yaznız: ")
for harf in kelime:
    print(harf)